#!/usr/bin/env bash
cd "$(dirname "$0")"
set -xeEuo pipefail

cd services

# Postgres

mkdir -p /data/postgres
podman create --name postgres \
  --network=podman \
  -e "POSTGRES_USER=%ARTIFACT%" \
  -e 'POSTGRES_PASSWORD=SomeP2assword!@e' \
  -e "POSTGRES_DB=%ARTIFACT%_dev" \
  -e "PGDATA=/var/lib/postgresql/data/pgdata" \
  -p 127.0.0.1:5432:5432 \
  -v /data/postgres:/var/lib/postgresql/data \
  postgres:15.2
podman generate systemd --new --files --name postgres


# app

mkdir -p /data/%ARTIFACT%-images
podman create --name %ARTIFACT% \
  --network=podman \
  -p 127.0.0.1:80:8080 \
  -e SPRING_PROFILES_ACTIVE=prod \
  -e SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/%ARTIFACT%_dev \
  -e SPRING_R2DBC_USERNAME=kotlin-bootstrap-app \
  -e 'SPRING_R2DBC_PASSWORD=SomeP2assword!@e' \
  -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/%ARTIFACT%_dev \
  -e SPRING_DATASOURCE_USERNAME=%ARTIFACT% \
  -e 'QUARKUS_DATASOURCE_PASSWORD=SomeP2assword!@e' \
  -e IMAGES_PATH=/data/%ARTIFACT%-images \
  -v /data/%ARTIFACT%-images/:/data \
  stepin/%ARTIFACT%
podman generate systemd --new --files --name %ARTIFACT%
